apiVersion: apps/v1
kind: Deployment
metadata:
  name: gataria-backend-catalog
  labels:
    app: gataria-backend-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gataria-backend-catalog
  template:
    metadata:
      labels:
        app: gataria-backend-catalog
    spec:
      containers:
      - name: gataria-backend-catalog
        image: mnogueiraops/gataria-backend-catalog:dev
        ports:
        - containerPort: 3010
    env:
      - name: MONGO_DATABASE
        value: "dev"
      - name: MONGO_URL
        value: "mongodb://gataria-db:42jOExwOyfT8iXOPFCbR3yjZCQhyrBrwk6qPJhyzYFSZXzN0m9ymhmxImdqXodLfKJDpro1ty168ACDbA7cfVw==@gataria-db.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@gataria-db@"