apiVersion: apps/v1
kind: Deployment
metadata:
  name: gataria-frontend
  labels:
    app: gataria-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gataria-frontend
  template:
    metadata:
      labels:
        app: gataria-frontend
    spec:
      containers:
      - name: gataria-frontend
        image: mnogueiraops/gataria-frontend:alpineprodtest
        ports:
        - containerPort: 3000