apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gataria-frontend
  spec:
    ingressClassName: nginx
    rules:
      - host: gataria.mnogueira.cloud
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: gataria-frontend                                              
                  port:
                    number: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    #tls:
      #- hosts:
        #- www.example.com
        #secretName: example-tls