apiVersion: apps/v1
kind: Deployment
metadata:
  name: gataria-backend-images
  labels:
    app: gataria-backend-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gataria-backend-images
  template:
    metadata:
      labels:
        app: gataria-backend-images
    spec:
      containers:
      - name: gataria-backend-images
        image: mnogueiraops/gataria-backend-images:dev
        ports:
        - containerPort: 3020
          env:
      - name: CATAPI_URL
      value: "https://api.thecatapi.com/v1/images/search"